version: '2'
services:
    nikrossshop-app:
        image: nikrossshop
        external_links:
            - nikrossshop-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/nikrossShop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nikrossshop-postgresql:
        extends:
            file: postgresql.yml
            service: nikrossshop-postgresql
